### ISSUE TITLE
cannot open "unread" and "recent"

### ISSUE THREAD

**Issue by AliCihan** [oplik0/nodebb-plugin-two-way-block#9] opened 2020-05-19 21:59 UTC
thanks for the plugin @oplik0 

we are having these problems in "recent" and "unread" posts pages... 

![Screen Shot 2020-05-19 at 5 52 31 PM](https://user-images.githubusercontent.com/52054408/82382494-13209e80-99fa-11ea-8bc3-da64aebf0f52.png)
![Screen Shot 2020-05-19 at 5 52 13 PM](https://user-images.githubusercontent.com/52054408/82382495-13b93500-99fa-11ea-94e0-7a93eb6ac4d8.png)

Although the blocked person just posted one post, it blocks the whole page to be seen. Additionally, it prevents the topics by the blocked person rather than blocking only his posts. 

And here are the logs:

`2020-05-19T21:50:24.705Z [4568/4527] - [31merror[39m: /api/recent
TypeError: Cannot read property 'uid' of undefined
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:50:57
    at Array.filter (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/nodebb/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:49:30)
2020-05-19T21:50:26.471Z [4568/4527] - [31merror[39m: /api/recent
TypeError: Cannot read property 'uid' of undefined
    at /home/nodebb/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:50:57
    at Array.filter (<anonymous>)
    at Object.twoWayBlock.filterTeasers [as method] (/home/nodebb/nodebb/node_modules/nodebb-plugin-two-way-block/library.js:49:30)
`

**Comment by oplik0** [comment] 2020-05-19 23:25
The main issue should be fixed in 1.3.0

> Additionally, it prevents the topics by the blocked person rather than blocking only his posts.

This is actually the intended behavior, apparently. The same thing happens if you block someone without the plugin. So if you believe this to be an incorrect behavior, report it to [NodeBB](https://github.com/NodeBB/NodeBB/issues).
[This line of code is to blame](https://github.com/NodeBB/NodeBB/blob/2a00b0e973ca6f2d04482f037afda5bc7a22b6b3/src/categories/topics.js#L16)

**Closed** 2020-05-19 23:25 UTC
